### ISSUE TITLE
Can't build on Arch Linux

### ISSUE THREAD

**Issue by telmotrooper** [plv8/plv8js#346]
Hello! I'm trying to **build and install plv8 on Arch Linux**, since the package on AUR (Arch User Repository) seems not to be working. I'm trying to manually build it with:

```
wget https://github.com/plv8/plv8/archive/v2.3.8.tar.gz
tar -xvzf v2.3.8.tar.gz
cd plv8-2.3.8
make
```

The problem is `make` returns the following output and does not finish execution:

```
Running: gclient root
WARNING: Your metrics.cfg file was invalid or nonexistent. A new one will be created.
Traceback (most recent call last):
  File "/home/telmo/plv8-2.3.8/build/depot_tools/fetch.py", line 318, in <module>
    sys.exit(main())
  File "/home/telmo/plv8-2.3.8/build/depot_tools/fetch.py", line 313, in main
    return run(options, spec, root)
  File "/home/telmo/plv8-2.3.8/build/depot_tools/fetch.py", line 299, in run
    if not options.force and checkout.exists():
  File "/home/telmo/plv8-2.3.8/build/depot_tools/fetch.py", line 98, in exists
    return (os.path.exists(os.path.join(gclient_root, '.gclient')) or
  File "/usr/lib/python3.7/posixpath.py", line 94, in join
    genericpath._check_arg_types('join', a, *p)
  File "/usr/lib/python3.7/genericpath.py", line 151, in _check_arg_types
    raise TypeError("Can't mix strings and bytes in path components") from None
TypeError: Can't mix strings and bytes in path components
```

Can someone help me with that?

**Comment by JerrySievert** [comment]
it looks like you're trying to build using `python` `3.7` - `v8` requires `python` `2` in order to build (`v8` is embedded in `plv8`).

see the notes here: https://plv8.github.io/#building

**Comment by telmotrooper** [comment]
I ended up creating a symbolic link for python2 as "python", another one for libtinfo.so.6 as libtinfo.so.5, installing libc++ from AUR and still I can't build it.

Now I'm stuck at:
```
./generate_upgrade.sh 2.3.8
sed -e 's/@PLV8_VERSION@/2.3.8/g' plv8.control.common | g++ -E -P -DLANG_plv8 - > plv8.control
sed -e 's/@LANG_NAME@/plv8/g' plv8.sql.common | sed -e 's/@PLV8_VERSION@/2.3.8/g' | g++ -E -P -I. -I./ -I/usr/include/postgresql/server -I/usr/include/postgresql/internal  -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE -I/usr/include/libxml2  -DLANG_plv8 - > plv8--2.3.8.sql
sed -e 's/@PLV8_VERSION@/2.3.8/g' plv8.control.common | g++ -E -P -DLANG_plcoffee - > plcoffee.control
sed -e 's/@LANG_NAME@/plcoffee/g' plv8.sql.common | sed -e 's/@PLV8_VERSION@/2.3.8/g' | g++ -E -P -I. -I./ -I/usr/include/postgresql/server -I/usr/include/postgresql/internal  -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE -I/usr/include/libxml2  -DLANG_plcoffee - > plcoffee--2.3.8.sql
sed -e 's/@PLV8_VERSION@/2.3.8/g' plv8.control.common | g++ -E -P -DLANG_plls - > plls.control
sed -e 's/@LANG_NAME@/plls/g' plv8.sql.common | sed -e 's/@PLV8_VERSION@/2.3.8/g' | g++ -E -P -I. -I./ -I/usr/include/postgresql/server -I/usr/include/postgresql/internal  -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE -I/usr/include/libxml2  -DLANG_plls - > plls--2.3.8.sql
make: *** No rule to make target 'plv8.bc', needed by 'all'.  Stop.
```

**Comment by JerrySievert** [comment]
there are 3 newer releases than `2.3.8` - the issue you are seeing was fixed in `2.3.9`, and is caused by build changes in Postgres.  you can see some discussion here: https://github.com/plv8/plv8/issues/304#issuecomment-445681959

**Comment by telmotrooper** [comment]
Okay, so besides doing what I did before and downloading [2.3.11](https://github.com/plv8/plv8/archive/v2.3.11.tar.gz), I also had to install the package "llvm". After that I was able to `make` and `make install` without errors, but I still can't use PLV8.

`SELECT plv8_version();` on **psql** gives me:
```
mydb=# SELECT plv8_version();
ERROR:  function plv8_version() does not exist
LINE 1: SELECT plv8_version();
               ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
```

And `make installcheck` gives me:
```
============== dropping database "contrib_regression" ==============
psql: FATAL:  role "telmo" does not exist
command failed: "/usr/bin/psql" -X -c "DROP DATABASE IF EXISTS \"contrib_regression\"" "postgres"
make: *** [/usr/lib/postgresql/pgxs/src/makefiles/pgxs.mk:403: installcheck] Error 2
```

**Comment by JerrySievert** [comment]
did you create the extension?

```
=# CREATE EXTENSION plv8;
```

**Comment by telmotrooper** [comment]
It seems I missed that step. It's working now, so thanks, @JerrySievert.

To summarize the whole thing for any other person who wants to use this on Arch Linux:
* You gotta install the packages libc++ (from AUR) and llvm
* Make a symbolic link so libtinfo.so.5 points to libtinfo.so.6 (you'll need this for compiling): `sudo ln -s /usr/lib/libtinfo.so.6 /usr/lib/libtinfo.so.5`
* Temporarily switch your default "python" to "python2" with `sudo rm /bin/python && sudo ln -s /bin/python2 /bin/python`
* Download the [latest version](https://github.com/plv8/plv8/releases/) for PLV8
* Extract, `make` and `sudo make install`
* Run `CREATE EXTENSION plv8;` in your database
* Test it with `SELECT plv8_version();`
* Return your default "python" to "python3" with `sudo rm /bin/python && sudo ln -s /bin/python3 /bin/python `

**Comment by JerrySievert** [comment]
you should only need `llvm` if your postgres is compiled with JIT, which yours was (or it would not have complained about the `bc` step)

**Comment by telmotrooper** [comment]
I installed it straight from the `postgresql` package from Arch's official repositories, so that's probably the way it's been compiled in the background.
